### ISSUE TITLE
file not found for module `addresses`

### ISSUE THREAD

**Issue by RedWilly** [Kuly14/frontrunning_bot#1]
got this error after running cargo build

file not found for module `addresses`
  --> src\lib.rs:13:1
   |
13 | pub mod addresses;
   | ^^^^^^^^^^^^^^^^^^
   |
   = help: to create the module `addresses`, create file "src\addresses.rs" or "src\addresses\mod.rs"

For more information about this error, try `rustc --explain E0583`.
error: could not compile `mev_bot` (lib) due to previous error

**Comment by Kuly14** [comment]
I fixed it but to be honest, unless you just want to learn from the code definitely don't use it.
